import ComboSalesOffer from "@/Components/ComboSalesOffer/ComboSalesOffer";
import React from "react";

export const metadata = {
  title: "Combo Sales",
  description: "Generated by create next app",
};

const ComboSales = () => {
  return <ComboSalesOffer />;
};

export default ComboSales;
