import ServicesPageContent from "@/Components/PagesComponents/ServicesPageContent/ServicesPageContent";
import UserLoading from "@/Components/Utilites/UserLoading/UserLoading";
import React, { Suspense } from "react";

export const metadata = {
  title: "Envobyte || Services",
  description: "Generated by create next app",
};

const ServicesPage = () => {
  return (
    <>
      <Suspense fallback={<UserLoading />}>
        <ServicesPageContent />
      </Suspense>
    </>
  );
};

export default ServicesPage;
