import ServicesPageContent from "@/Components/PagesComponents/ServicesPageContent/ServicesPageContent";
import { allsServiceItemsApi, serviceListApi } from "@/config/apis";
import React from "react";

export const metadata = {
  title: "Envobyte || Services",
  description: "Generated by create next app",
};

async function getServices() {
  try {
    const [res1, res2] = await Promise.all([
      fetch(`${serviceListApi}`, { next: { revalidate: 10 } }),
      fetch(`${allsServiceItemsApi}`, { next: { revalidate: 10 } }),
    ]);

    if (!res1.ok || !res2.ok) {
      throw new Error("Failed to fetch data");
    }

    const serviceCategories = await res1.json();
    const services = await res2.json();

    return { serviceCategories, services };
  } catch (error) {
    console.error("Error fetching data:", error);
    throw error;
  }
}

const ServicesPage = async () => {
  const { serviceCategories, services } = await getServices();

  return (
    <>
      <ServicesPageContent
        serviceCategories={serviceCategories}
        services={services}
      />
    </>
  );
};

export default ServicesPage;
