import { Inter } from "next/font/google";
import "/src/styles/globals.css";
import { Toaster } from "react-hot-toast";
import DashBoardSideNav from "@/Components/Dashboard/DashBoardSideNav";
import DashBoardNav from "@/Components/Dashboard/DashBoardNav";
import AuthProviders from "@/providers/AuthProviders";
import { Suspense } from "react";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Envobyte Ltd",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <link
        rel="icon"
        href="https://i.ibb.co/nM2nH6n/android-chrome-256x256.png"
        sizes="any"
      />
      <body className={inter.className}>
        <div className="bg-[#8CD3FB1A] fixed w-full">
          <div>
            <div className="w-full flex bg-[#fff]">
              <AuthProviders>
                <DashBoardSideNav height="100vh" />
                <div className="w-full ">
                  <Suspense>
                    <DashBoardNav />
                  </Suspense>
                  <div className="bg-[#000] px-[5%] md:px-0 w-full">
                    {children}
                  </div>
                </div>
              </AuthProviders>
            </div>
          </div>
        </div>
        <Toaster />
      </body>
    </html>
  );
}
