import AppHeader from "@/Components/Utilites/AppContents/AppHeader";
import "../globals.css";
import AppFooter from "@/Components/Utilites/AppContents/AppFooter";

export const metadata = {
  title: "Appsuite | Home",
  description: "Generated by create next app",
  icons: {
    icon: [
      { url: "/assets/Appsuitelogo_small.jpg", sizes: "32x32" },
      { url: "/assets/Appsuitelogo_small.jpg", sizes: "16x16" },
    ],
    apple: [{ url: "/apple-icon.png", sizes: "180x180" }],
  },
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <AppHeader />
        {children}
        <AppFooter />
      </body>
    </html>
  );
}
