import ComboLead from "@/Components/ComboLead/ComboLead";
import { fetchData } from "@/config/fetchData";

async function getPageData() {
  try {
    return await fetchData("/comboservices");
  } catch (error) {
    console.error("Error fetching home page data:", error);
    throw error;
  }
}

export const metadata = {
  title: "Combo Lead",
  description: "Generated by create next app",
};

const ComboLeadPage = async () => {
  const homeData = await getPageData();

  return (
    <>
      <ComboLead homeData={homeData} />
    </>
  );
};

export default ComboLeadPage;
