import { Inter } from "next/font/google";
import "/src/styles/globals.css";
import { Footer } from "@/Components";
import Header from "@/Components/Home/Navbar/Header";
import { Toaster } from "react-hot-toast";
import AuthProviders, { ThemeProvider } from "@/providers/AuthProviders";
import GoogleTagManagerScript from "../GoogleTagManager/GoogleTagManagerScript";
import GoogleTagManagerNoScript from "../GoogleTagManager/GoogleTagManagerNoScript";
import HubSpotScript from "@/Components/HubSpot/HubSpot";
import HotJar from "../Hotjar/HotJar";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Envobyte Ltd || Home",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link
          rel="icon"
          href="https://i.ibb.co/nM2nH6n/android-chrome-256x256.png"
          sizes="16x16"
        />
        <GoogleTagManagerScript />
        <HotJar />
      </head>
      <body className={inter.className}>
        <GoogleTagManagerNoScript />

        <Toaster />
        <AuthProviders>
          <Header />
          {children}
          <HubSpotScript />
          <Footer />
        </AuthProviders>
      </body>
    </html>
  );
}
