import { Inter } from "next/font/google";
import "../globals.css";
import { Footer } from "@/Components";
import Header from "@/Components/Home/Navbar/Header";
import { Toaster } from "react-hot-toast";
import AuthProviders, { ThemeProvider } from "@/providers/AuthProviders";
import GoogleTagManagerScript from "../GoogleTagManager/GoogleTagManagerScript";
import GoogleTagManagerNoScript from "../GoogleTagManager/GoogleTagManagerNoScript";
import Analytics from "../Analytics/Analytics";
import HubSpotScript from "@/Components/HubSpot/HubSpot";
import HotJar from "../Hotjar/HotJar";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Envobyte Ltd || Home",
  description: "Generated by create next app",
  icons: {
    icon: [
      { url: "/favicon.ico", sizes: "32x32" },
      { url: "/favicon.ico", sizes: "16x16" },
    ],
    apple: [{ url: "/assets/Appsuitelogo_small.jpg", sizes: "180x180" }],
  },
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <GoogleTagManagerScript />
        <Analytics />
        <HotJar />
      </head>
      <body className={inter.className}>
        <GoogleTagManagerNoScript />
        <Toaster />
        <AuthProviders>
          <Header />
          {children}
          <HubSpotScript />
          <Footer />
        </AuthProviders>
      </body>
    </html>
  );
}
