import PortfolioPage from "@/Components/PagesComponents/PortfolioPage/PortfolioPage";
import { serviceListApi, sevice_portfolioApi } from "@/config/apis";
import { apiEndpoint } from "@/config/config";

export const metadata = {
  title: "Envobyte || Portfolio ",
  description: "Generated by create next app",
};

async function portfolioServices() {
  const res = await fetch(
    `http://192.168.10.14:8000/api/sevice_portfolio_update`,
    {
      next: { revalidate: 10 },
    }
  );

  if (!res.ok) {
    throw new Error("Failed to fetch data");
  }
  return res.json();
}
async function portfoliosCategoriesApi() {
  const res = await fetch(`${serviceListApi}`, {
    next: { revalidate: 10 },
  });

  if (!res.ok) {
    throw new Error("Failed to fetch data");
  }
  return res.json();
}
async function servicesApi() {
  const res = await fetch(`${apiEndpoint}/search_sevice_category/all`, {
    next: { revalidate: 10 },
  });

  if (!res.ok) {
    throw new Error("Failed to fetch data");
  }
  return res.json();
}

const Portfolio = async () => {
  // Fetch data for the page

  const portfolios = await portfolioServices();
  const portfoliosCategories = await portfoliosCategoriesApi();
  const services = await servicesApi();
  // console.log(portfolios);

  return (
    <div className="max-w-[1520px] mx-auto px-[6%] md:px-[4%] lg:px-[1%] 4xl:px-[2%]">
      <PortfolioPage
        portfolios={portfolios}
        portfoliosCategories={portfoliosCategories}
        services={services}
      />
    </div>
  );
};

export default Portfolio;
