import Container from "@/Components/Container/Container";
import PortfolioPage from "@/Components/PagesComponents/PortfolioPage/PortfolioPage";
import UserLoading from "@/Components/Utilites/UserLoading/UserLoading";
import { serviceListApi, sevice_portfolioApi } from "@/config/apis";
import { apiEndpoint } from "@/config/config";
import { Suspense } from "react";
export const metadata = {
  title: "Envobyte || Portfolio ",
  description: "Generated by create next app",
};

async function portfolioCategory() {
  const res = await fetch(`${sevice_portfolioApi}`, {
    next: { revalidate: 10 },
  });

  if (!res.ok) {
    throw new Error("Failed to fetch data");
  }
  return res.json();
}
async function portfoliosCategoriesApi() {
  const res = await fetch(`${serviceListApi}`, {
    next: { revalidate: 10 },
  });

  if (!res.ok) {
    throw new Error("Failed to fetch data");
  }
  return res.json();
}
async function servicesApi() {
  const res = await fetch(`${apiEndpoint}/search_sevice_category/all`, {
    next: { revalidate: 10 },
  });

  if (!res.ok) {
    throw new Error("Failed to fetch data");
  }
  return res.json();
}

const Portfolio = async () => {
  // Fetch data for the page

  const portfolios = await portfolioCategory();
  const portfoliosCategories = await portfoliosCategoriesApi();
  const services = await servicesApi();
  // console.log(services);

  return (
    <>
      <Suspense fallback={<UserLoading />}>
        <Container>
          <PortfolioPage
            portfolios={portfolios}
            portfoliosCategories={portfoliosCategories}
            services={services}
          />
        </Container>
      </Suspense>
    </>
  );
};

export default Portfolio;
