import Container from "@/Components/Container/Container";
import React from "react";

export const metadata = {
  title: "Envobyte Ltd || Terms and conditions",
  description: "Generated by create next app",
};

const Terms = () => {
  return (
    <Container>
      <div className="bg-gray-100 mt-5 px-10">
        <div className="container mx-auto px-4 py-8">
          {/* general */}
          <div>
            <h1 className="text-4xl font-bold mb-8 text-center">
              TERMS OF USE
            </h1>

            <p className="mb-4">
              These Terms of Use (“Terms”) govern your use of Envobyte’s
              (“Envobyte”) website (the “Site”). Please read the Terms before
              using the Site. Use of the Site constitutes your agreement to all
              Terms. If you object to anything in these Terms or the Site’s
              Privacy Policy, please do not use the Site. The Terms are subject
              to change at any time, effective upon posting on the Site.
            </p>

            <h2 className="text-2xl font-bold mb-2">
              PRIVACY AND PROTECTION OF PERSONAL INFORMATION
            </h2>

            <p className="mb-4">
              See the privacy statement for disclosures relating to the
              collection and use of your information.
            </p>

            <h2 className="text-2xl font-bold mb-2">WEBSITE CONTENT</h2>
            <p className="mb-4">
              All content available on the Site is the copyrighted work of
              Envobyte. Any reproduction or redistribution of this Site, in
              whole or in part, without the written permission of Envobyte is
              expressly prohibited by law, and may result in civil and criminal
              penalties. All text, graphics, editorial content, data,
              formatting, graphs, designs, HTML, look and feel, photographs,
              music, sounds, images, software, videos, designs, typefaces and
              other content (collectively “Proprietary Material”), as well as
              the coordination, selection, arrangement and enhancement of such
              Proprietary Material, that users see or read on the Site is owned
              by Envobyte or is used with permission. This Proprietary Material
              is protected in all forms, media and technologies now known or
              hereinafter developed. Users may not copy, download, use redesign,
              reconfigure, or retransmit anything from the Site without
              Envobyte’s prior express written permission.
            </p>
            <p className="mb-4">
              Envobyte makes no representations about the suitability of the
              information or content contained on the Site for any purpose. All
              such materials are provided “as is” without warranty of any kind.
              Envobyte disclaims all warranties and conditions with regard to
              the Site, including all warranties and conditions of
              merchantability, whether express, implied or statutory, fitness
              for a particular purpose, title and non-infringement. In no event
              shall Envobyte be liable for any special, indirect or
              consequential damages or any damages whatsoever resulting from
              loss of use, data or profits, whether in an action of contract,
              negligence or other tortious action, arising out of or in
              connection with the use of information available from the Site.
            </p>

            <h2 className="text-2xl font-bold mb-2">
              NO UNLAWFUL OR PROHIBITED USE
            </h2>

            <p className="mb-4">
              As a condition of your use of the Site, you will not use the Site
              for any purpose that is unlawful or prohibited by these terms,
              conditions, and notices. You may not use the Site in any manner
              that could damage, disable, overburden, or impair the Site or the
              servers that host it, or interfere with any other party’s use and
              enjoyment of the Site. You may not attempt to gain unauthorized
              access to the Site, or accounts, computer systems or networks that
              may be accessed through the Site, through hacking, password mining
              or any other means. You may not obtain or attempt to obtain any
              materials or information through any means not intentionally made
              available through the Site.
            </p>

            <p className="mb-4">
              Envobyte may terminate your access to the Site at any time and for
              any reason with or without notice to you. Envobyte shall not be
              liable to you for any loss associated with termination of such
              access.
            </p>

            <h2 className="text-2xl font-bold mb-2">
              LINKS TO THIRD PARTY SITES
            </h2>

            <p className="mb-4">
              Links from the Site to other sites on the Web, if any, are
              provided as an information service only. It is the responsibility
              of the user to evaluate the content and usefulness of the
              information obtained from other sites. Envobyte does not control
              such websites, and is not responsible for their content. Users
              further acknowledge that use of any website controlled, owned or
              operated by third parties is governed by the terms and conditions
              of use for those websites, and not by Envobyte’s Terms of Use and
              Privacy Policy. All users do hereby agree to hold Envobyte
              harmless from any liability that may result from the use of links
              that may appear on the Site.
            </p>

            <h2 className="text-2xl font-bold mb-2">
              MODIFICATIONS TO THE SITE
            </h2>
            <p className="mb-4">
              Envobyte reserves the right in its sole discretion to review,
              improve, modify or discontinue, temporarily or permanently, the
              Site or any content or information on the Site with or without
              notice to the user and Envobyte shall not be liable to user or any
              third party for any modification or discontinuance of the Site.
            </p>

            <h2 className="text-2xl font-bold mb-2">MISCELLANEOUS</h2>
            <p className="mb-4">
              Failure by Envobyte to enforce any provision(s) of these Terms
              shall not be construed as a waiver of any provision or right.
              These Terms, and all other aspects of use of the Site, shall be
              governed by and construed in accordance with the laws of the
              Bangladesh, without regard to its conflict of laws rules. All
              claims and disputes arising out of these Terms or use of the Site
              shall be exclusively brought in the federal, state or local courts
              located in Tayamun Center (3rd floor), 181/1 Jessore Road, Khulna,
              Bangladesh; and, with regard to such claims and disputes, Users
              hereby irrevocably (i) submit to the exercise of personal
              jurisdiction over them by these courts, and (ii) waive any
              jurisdictional, venue or inconvenient forum objections to such
              courts. If any provision of these Terms is found to be invalid or
              unenforceable, the remaining provisions shall be enforced to the
              fullest extent possible, and the remaining Terms shall remain in
              full force and effect.
            </p>
          </div>
        </div>
      </div>
    </Container>
  );
};

export default Terms;
