import AboutUsContent from "@/Components/PagesComponents/AboutUsContent/AboutUsContent";
import { aboutUsApi, aboutUsItemApi } from "@/config/apis";
import React from "react";

export const metadata = {
  title: "Envobyte || About Us",
  description: "Generated by create next app",
};

async function getAboutPage() {
  const res = await fetch(`${aboutUsApi}`, {
    next: { revalidate: 10 },
  });

  if (!res.ok) {
    throw new Error("Failed to fetch data");
  }
  return res.json();
}

async function getAbout_item() {
  const res = await fetch(`${aboutUsItemApi}`, {
    next: { revalidate: 10 },
  });

  if (!res.ok) {
    throw new Error("Failed to fetch data");
  }
  return res.json();
}

const AboutUsPage = async () => {
  const aboutDetails = await getAboutPage();
  const singleAboutDetails = await getAbout_item();
  return (
    <>
      <AboutUsContent
        aboutDetails={aboutDetails}
        singleAboutDetails={singleAboutDetails}
      />
    </>
  );
};

export default AboutUsPage;
