import Container from "@/Components/Container/Container";
import React from "react";

export const metadata = {
  title: "Envobyte Ltd || Refund Policy",
  description: "Generated by create next app",
};

const RefundPolicy = () => {
  return (
    <Container>
      <div className="bg-gray-100  px-8 mt-5 pb-8 pt-5">
        <h1 className="text-4xl font-bold mb-4 text-center pt-3">
          Refund Policy
        </h1>
        <section className="mb-8">
          <h2 className="text-xl font-semibold mb-2">Disclaimer</h2>
          <p className="mb-4">
            THE PRODUCTS AND SERVICES ARE PROVIDED on an “AS IS” and “AS
            AVAILABLE” BASIS AND ENVOBYTE EXPRESSLY DISCLAIMS ALL OTHER
            WARRANTIES, EXPRESS AND IMPLIED, INCLUDING BUT NOT LIMITED TO, THE
            IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR
            PURPOSE.
          </p>
        </section>
        <section className="mb-8">
          <h3 className="text-xl font-bold mb-4 text-left">Refund Policy:</h3>

          <p className="mb-4">Envobyte will entertain refunds on:</p>

          <ul className="list-disc list-inside mb-4">
            <li>
              Once work on a project has commenced, any cancellation initiated
              by the client will result in a partial refund. The refund amount
              will be adjusted based on the proportion of work completed up to
              the point of cancellation.
            </li>
            <li>
              Service Requirements not met: If Envobyte can&apos;t complete
              project requirement, subject to clear, straightforward
              communication on part of the client, provided any and all
              pre-requisites including but not limited to content, graphics,
              specifications, and channels are mentioned. Any additional
              requirements made after the purchase will not be refunded. Before
              starting project, client will have to submit all requirement from
              Requirement Submit page. Any additional changes made during the
              process will not be included in the refund.
            </li>
            <li>
              Timeline is not met: Refunds can only be claimed if 2x of service
              timeline has been passed. In short, if the service has been given
              5 days timeline and 10 business day are gone, the user can claim
              Refund.
            </li>
            <li>
              Service Days and Business Days: Be advised that Service days
              include Monday thru Friday, whereas, Saturdays&Sundays are
              excluded from business days.
            </li>
          </ul>

          <div className="flex flex-col gap-y-2">
            <span className="py-4">
              Without Service or Timeline restrictions, if any user claims
              refund then Envobyte will settle the matter on merit of the
              validity of the claim. Envobyte reserves the right to accept or
              reject any claims, and the management decision will be considered
              final.
            </span>{" "}
            <span>
              NO REFUND WILL BE ENTERTAINED IF A PROJECT IS DELAYED AT THE
              REQUEST OF THE CLIENT, DUE TO THE CLIENT&apos;S INTERNAL
              PROCESSES, LACK OF COMMUNICATION, AND EXPLICIT INSTRUCTIONS ON
              PART OF THE CLIENT.{" "}
            </span>
          </div>

          <h3 className="text-xl font-bold mb-4 text-left pt-3">
            Changes to payment and refund policy:
          </h3>

          <p>
            We reserve the right to change this refunds policy terms and
            conditions at any time. Any such changes will take effect when
            posted on the website.
          </p>
        </section>

        <section id="working_days" className="mb-8">
          <h2 className="text-xl font-semibold mb-2">Our Working Days</h2>
          <p className="mb-4">
            All days are business days except Friday and Saturday.
          </p>
        </section>
      </div>
    </Container>
  );
};

export default RefundPolicy;
